WITH SRC_TRUCK AS (
    SELECT * FROM {{ source('pos', 'truck') }}
)

SELECT 
    TRUCK_ID,
    MENU_TYPE_ID,
    PRIMARY_CITY,
    REGION,
    ISO_REGION,
    COUNTRY,
    ISO_COUNTRY_CODE,
    FRANCHISE_FLAG,
    YEAR,
    MAKE,
    MODEL,
    EV_FLAG,
    FRANCHISE_ID,
    TRUCK_OPENING_DATE
FROM SRC_TRUCK